### ISSUE TITLE
esp-idf-ftpServer for SoftAP (not STA)

### ISSUE THREAD

**Issue by filo38** [nopnop2002/esp-idf-ftpServer#10]
Do it possible porting the project in SoftAP mode? Thanks you

**Comment by nopnop2002** [comment]
It's not difficult, but I can't think of a situation to use it in AP mode.

I would like to know how you plan to use it.

**Comment by filo38** [comment]
Our intention is to make a wifi direct

**Comment by nopnop2002** [comment]
Try latest.

**Comment by filo38** [comment]
Thanks you very much, we try the new project.
I will inform you about our job.


ps: I use the demo board "Panasonic Evaluation Kit" and Eclipse IDE, but I not able to debug, are there same tricks?
Thanks you

**Comment by nopnop2002** [comment]
Fixed a bug in AP mode.

Try latest.
