### ISSUE TITLE
Looking forward to USB Memory Stick support！

### ISSUE THREAD

**Issue by twuking** [nopnop2002/esp-idf-ftpServer#13]
Am planning to support USB Memory Stick, can you provide some ideas?

I found that USB Memory Stick and Fat filesystem support has been implemented in this link, clueless as to how to embed it in an ftp server. Thanks for your reply.

https://github.com/espressif/esp-dev-kits/tree/ac453a16cc46b04304431dbca2acdd4130df2737/esp32-s3-lcd-ev-board/examples/usb_msc_file_sys

**Comment by nopnop2002** [comment]
There is official example code here.
However, writing to a memory stick is very slow.
That's why we're not supporting Memory Stick.

https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/msc

**Comment by twuking** [comment]
Has there been any consideration of webDav support?

**Comment by nopnop2002** [comment]
I have never used webDav.

First, let's find out how to use it.

**Comment by nopnop2002** [comment]
>Has there been any consideration of webDav support?

Try this.

https://github.com/nopnop2002/esp-idf-webdav-client

**Comment by twuking** [comment]
👍 Good Job  ,Thx
