### ISSUE TITLE
About Esp32-Cam

### ISSUE THREAD

**Issue by ghost** [nopnop2002/esp-idf-ftpServer#5]
Can we use that project at Esp32-Cam

**Comment by nopnop2002** [comment]
I tried this.

![ESP32-CAM-1](https://user-images.githubusercontent.com/6020549/113945391-35edb880-9841-11eb-920c-cff49d4abe34.JPG)
![ESP32-CAM-2](https://user-images.githubusercontent.com/6020549/113945396-371ee580-9841-11eb-996b-2ea25b5d6647.JPG)


```
cd esp-idf-ftpServer/
idf.py set-target esp32
idf.py menuconfig
idf.py flash monitor
```

It's no problem.
If you get Brownout, you need stable power source.

![ftpServer](https://user-images.githubusercontent.com/6020549/113946862-58350580-9844-11eb-9acf-cbc6cb1ec756.jpg)

**Comment by ghost** [comment]
> I tried this.
> cd esp-idf-ftpServer/
> idf.py set-target esp32
> idf.py menuconfig
> idf.py flash monitor
> ```


Thanks for the reply. I want to transfer file between a pc and esp32-camera, they are gonna connect same LAN but that network has no access to the Internet to sync time , is time necessary for ftp? can I sync time from another source like a TCP/IP message from pc or UART receive from another microprocessor with Real Time Clock in it?  
When I tried to compile and flash the commands you wrote above it gave an error about "PIN_POWER" for now its not a problem ftp is above storage it seems fixable.

**Comment by nopnop2002** [comment]
>is time necessary for ftp?

Yes.
An accurate GMT time is required to record the time the file was saved.

>can I sync time from another source like a TCP/IP message from pc or UART receive from another microprocessor with Real Time Clock in it?

The solution is to install an NTP server software on the PC side.
The PC becomes an NTP server and time synchronization is performed.

>it gave an error about "PIN_POWER"

I have never seen this error.

**Comment by ghost** [comment]
> > is time necessary for ftp?
> 
> Yes.
> An accurate GMT time is required to record the time the file was saved.
> 
> > can I sync time from another source like a TCP/IP message from pc or UART receive from another microprocessor with Real Time Clock in it?
> 
> The solution is to install an NTP server software on the PC side.
> The PC becomes an NTP server and time synchronization is performed.
> 
> > it gave an error about "PIN_POWER"
> 
> I have never seen this error.

**Comment by ghost** [comment]
ok it works on SD card on SPI mode, MCC mode gives compile error. Thanks for fast replies , i hope i didnt bothered you. Now im facing another problem, i can upload several files types but mp4 files maybe its fixable.
Thanks for answers and great work.

**Comment by nopnop2002** [comment]
>MCC mode gives compile error.

Thank you for your report.
Fixed it.

>but mp4 files maybe its fixable.

How big is your mp4 file?

**Comment by ghost** [comment]
> > MCC mode gives compile error.
> 
> Thank you for your report.
> Fixed it.
> 
> > but mp4 files maybe its fixable.
> 
> How big is your mp4 file?
Tested over 7mb it works i think it was about file name. I uploaded and downloaded for testing, it seems works perfectly. Thanks again.

**Comment by nopnop2002** [comment]
>Tested over 7mb it works i think it was about file name. I uploaded and downloaded for testing, it seems works perfectly.

Good!
