### ISSUE TITLE
FTP client in C# Exceptions

### ISSUE THREAD

**Issue by mehceunisen** [nopnop2002/esp-idf-ftpServer#6]
First of all thanks, this server library worked out quite efficiently but I've had a problem while I was trying to upload a file to FTP server which it is Esp-32. I coded FTP client on C# and I'm having "Unable to connect to the remote server" exception. Have you got any idea about this? 
Thanks...

**Comment by nopnop2002** [comment]
The server does not support active connection. Only passive connection.

**Comment by MehceUnisen** [comment]
I'm already trying to upload file passively. I'm thinking about maybe the ftp server address is wrong. For example "ftp://192.168.1.102:21", is this a right address, becasue FTP runs on TCP and if I get no response there is limited probabilities such as wrong address or firewall blocking the port. Also I know that firewall is not blocking the port.

**Comment by nopnop2002** [comment]
I have never used C#'s FTP CLIENT.

If the connection is correct with an application like FileZilla, the address and port may be specified incorrectly.

----

Windows 10 has an FTP server function by default, but it is disabled by default. 

https://www.windowscentral.com/how-set-and-manage-ftp-server-windows-10

Try to connect to the Windows 10 FTP Server from C#.

**Comment by mehceunisen** [comment]
Ok, I will try that. Thanks for help.
