### ISSUE TITLE
data socket disconnected in reading a file from sdcard 

### ISSUE THREAD

**Issue by mhsoftware100** [nopnop2002/esp-idf-ftpServer#7]
[](url)I program this project in esp32 through serial port. I can connect to esp32 width ftp client and I can 
Login width default user and password.
I can rename and delete files in sdcard and there is not problem in file system and network connectivity.

But I can not get a file or put a file in sdcard 

what is the problem?
![ftp](https://user-images.githubusercontent.com/77447852/131277186-661c9e1b-d815-4e4d-8af6-096babf3ebeb.png)

![image](https://user-images.githubusercontent.com/77447852/131277243-e0438bee-3bf8-464b-99ea-a7426f4d11f1.png)

**Comment by nopnop2002** [comment]
The server does not support active connection. 
__Only passive connections are supported.__

Unfortunately, Windows standard ftp.exe does not allow passive mode (PASV) connections.


If you have to make a passive mode connection On Windows, you need to use another software such as FFFTP / WinSCP / FileZilla to connect in passive mode.

**Comment by mhsoftware100** [comment]
thank you 

I download and install Filezilla software and try to connect to the FTP Server But I could not connect 

I don't know what is the problem ?!

![image](https://user-images.githubusercontent.com/77447852/131376896-744520fb-4f04-4067-b64f-21fd686fb4b0.png)

**Comment by nopnop2002** [comment]
This is mine.
```
I (0) cpu_start: App cpu up.
I (416) cpu_start: Pro cpu start user code
I (416) cpu_start: cpu freq: 240000000
I (416) cpu_start: Application information:
I (421) cpu_start: Project name:     ftpServer
I (426) cpu_start: App version:      1
I (430) cpu_start: Compile time:     Aug 31 2021 06:33:32
I (437) cpu_start: ELF file SHA256:  f58f8b16574e30b6...
I (442) cpu_start: ESP-IDF:          v4.4-dev-2825-gb63ec47238
I (449) heap_init: Initializing. RAM available for dynamic allocation:
I (456) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (462) heap_init: At 3FFB7D20 len 000282E0 (160 KiB): DRAM
I (469) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (475) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (481) heap_init: At 400944BC len 0000BB44 (46 KiB): IRAM
I (488) spi_flash: detected chip: generic
I (492) spi_flash: flash io: dio
I (497) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (550) MAIN: ESP_WIFI_MODE_STA
I (550) MAIN: ESP-IDF Ver4.4
I (550) MAIN: ESP-IDF esp_netif
I (570) wifi:wifi driver task: 3ffc0f54, prio:23, stack:6656, core=0
I (570) system_api: Base MAC address is not set
I (570) system_api: read default base MAC address from EFUSE
I (580) wifi:wifi firmware version: d683787
I (590) wifi:wifi certification version: v7.0
I (590) wifi:config NVS flash: enabled
I (590) wifi:config nano formating: disabled
I (590) wifi:Init data frame dynamic rx buffer num: 32
I (590) wifi:Init management frame dynamic rx buffer num: 32
I (600) wifi:Init management short buffer num: 32
I (600) wifi:Init dynamic tx buffer num: 32
I (610) wifi:Init static rx buffer size: 1600
I (610) wifi:Init static rx buffer num: 10
I (620) wifi:Init dynamic rx buffer num: 32
I (620) wifi_init: rx ba win: 6
I (620) wifi_init: tcpip mbox: 32
I (630) wifi_init: udp mbox: 6
I (630) wifi_init: tcp mbox: 6
I (640) wifi_init: tcp tx win: 5744
I (640) wifi_init: tcp rx win: 5744
I (640) wifi_init: tcp mss: 1440
I (650) wifi_init: WiFi IRAM OP enabled
I (650) wifi_init: WiFi RX IRAM OP enabled
I (660) wifi:Set ps type: 0

I (680) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
W (680) phy_init: failed to load RF calibration data (0xffffffff), falling back to full calibration
I (840) wifi:mode : sta (fc:f5:c4:01:04:6c)
I (840) wifi:enable tsf
I (850) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (1360) wifi:state: init -> auth (b0)
I (1370) wifi:state: auth -> assoc (0)
I (1380) wifi:state: assoc -> run (10)
W (1390) wifi:<ba-add>idx:0 (ifx:0, f8:b7:97:36:de:52), tid:5, ssn:0, winSize:64
I (1490) wifi:connected with aterm-d5a4ee-g, aid = 3, channel 1, BW20, bssid = f8:b7:97:36:de:52
I (1490) wifi:security: WPA2-PSK, phy: bgn, rssi: -40
I (1500) wifi:pm start, type: 0

W (1500) wifi:<ba-add>idx:1 (ifx:0, f8:b7:97:36:de:52), tid:0, ssn:2, winSize:64
I (1670) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (2560) esp_netif_handlers: sta ip: 192.168.10.158, mask: 255.255.255.0, gw: 192.168.10.1
I (2560) MAIN: got ip:192.168.10.158
I (2560) MAIN: connected to ap SSID:aterm-d5a4ee-g password:
I (2570) MAIN: wifi_init_sta finished.
I (2570) MAIN: connect to ap SSID:aterm-d5a4ee-g
I (2580) MAIN: mdns hostname set to: [ftp-server]
I (2580) MAIN: IP Address : 192.168.10.158
I (2590) MAIN: Subnet mask: 255.255.255.0
I (2590) MAIN: Gateway    : 192.168.10.1
I (2600) MAIN: Getting time over NTP.
I (2600) MAIN: Initializing SNTP
I (2600) MAIN: Your NTP Server is pool.ntp.org
I (2610) MAIN: Waiting for system time to be set... (1/10)
I (3970) MAIN: Notification of a time synchronization event
W (3980) wifi:<ba-add>idx:2 (ifx:0, f8:b7:97:36:de:52), tid:6, ssn:1, winSize:64
I (4620) MAIN: The local date/time is: Tue Aug 31 06:34:40 2021
W (4620) MAIN: This server manages file timestamps in GMT.
I (4620) MAIN: Initializing FAT file system
W (4810) vfs_fat_spiflash: f_mount failed (13)
I (4810) vfs_fat_spiflash: Formatting FATFS partition, allocation unit size=4096
I (5300) vfs_fat_spiflash: Mounting again
I (5300) MAIN: Mount FAT filesystem on /root
I (5300) MAIN: s_wl_handle=0
I (5300) [Ftp]: ftp_task start
```


![filezilla](https://user-images.githubusercontent.com/6020549/131409720-186b8d5d-5457-434c-93c1-5c5eec245ced.jpg)

**Comment by mhsoftware100** [comment]
thank you 

I can connect and login and list directory but the information of the list directory are not correct!

It does not display names and sizes and other information about the files and directories!

![image](https://user-images.githubusercontent.com/77447852/131436241-6a70f5f1-36a9-481c-b40e-f76d33675658.png)

**Comment by nopnop2002** [comment]
Which of the following file systems are you using?
- FAT file system on FLASH
- FAT file system on SPI peripheral SDCARD
- FAT file system on SDMMC peripheral SDCARD

If you are using SD CARD, I want to know the filenames that exist in SD CARD.
Server don't support non-ASCII file name & directory.

**Comment by mhsoftware100** [comment]
I use FAT file system on SPI peripheral SDCARD

**Comment by nopnop2002** [comment]
What does that SDCATD look like when opened in Windows Explorer ?

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131598129-6499a88d-1680-4a64-9678-144af63faece.png)

![image](https://user-images.githubusercontent.com/77447852/131598190-bb81f6d8-1620-455a-bb54-337b148f1fbb.png)

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131598288-e204771f-6e37-4eab-a31e-78ad46b2cb52.png)

**Comment by mhsoftware100** [comment]
This my FAT Configuration 

![image](https://user-images.githubusercontent.com/77447852/131598509-827ced06-a997-4892-af07-9870c60181b0.png)

**Comment by mhsoftware100** [comment]
There is another problem in uploading a file 
When I want to upload a file It does not work put command correctly


![image](https://user-images.githubusercontent.com/77447852/131599774-a8252991-fa2e-40d4-bfe9-0140cc561e9c.png)

In this state  If I connect again It's starting to upload!

what is the problem?

**Comment by nopnop2002** [comment]
Try increasing this value to 16.

https://github.com/nopnop2002/esp-idf-ftpServer/blob/main/main/main.c#L243

**Comment by mhsoftware100** [comment]
I changed the value to 16 but It doesn't effect 

I have two problems now :

1. I connect and list directory but the information of the directory is not correct and it doesn't show the size and the file name of the files and directories 

2. after being connected to the FTP Server I can not upload a file

**Comment by nopnop2002** [comment]
Can you compress the contents of the SD card and post it here?

Then I can get the same SD card as you.

**Comment by mhsoftware100** [comment]
[sdcard.zip](https://github.com/nopnop2002/esp-idf-ftpServer/files/7096741/sdcard.zip)

**Comment by mhsoftware100** [comment]
[project.zip](https://github.com/nopnop2002/esp-idf-ftpServer/files/7096784/project.zip)

This is my FTP Server ESP32S2 IDF Project Source files

**Comment by nopnop2002** [comment]
Thank you for providing the file.

I copied all the files to a newly formatted SD card.

It was displayed correctly in FileZila.
![fileZilla-1](https://user-images.githubusercontent.com/6020549/131810606-0b1be7ad-66c1-45fb-a694-2a3d2008a476.jpg)


Perhaps something is wrong with the format of your SD card.

Try using a new SD card.

Second, FileZilla doesn't work properly for uploading files.
I don't know why.
![fileZilla-2](https://user-images.githubusercontent.com/6020549/131810643-ffcb6658-ef03-4f43-aaf0-7f43a6315d13.jpg)


So I used ffftp.
I found a Delete bug in the current repository.

In the latest version + ffftp, Upload and Delete of files work correctly.

![ffftp-1](https://user-images.githubusercontent.com/6020549/131810687-5126c54d-52e4-4534-a3da-70f7804f229c.jpg)

Upload file to server:      
![ffftp-2](https://user-images.githubusercontent.com/6020549/131810693-1cde0a76-4022-4c9a-a2fc-2c3782a6495c.jpg)

Delete file from server:   
![ffftp-3](https://user-images.githubusercontent.com/6020549/131810678-dedab4a4-86f3-41d4-bf49-14bf74d4235b.jpg)

---

Please try under the following conditions

- New SD card.
- Latest version.
- ffftp

**Comment by nopnop2002** [comment]
You need to make this setting when using FileZilla.

File->Site Manager->New site
![fileZilla-1](https://user-images.githubusercontent.com/6020549/131815967-e4d18368-d57e-4506-9423-d91a74f25587.jpg)

![fileZilla-2](https://user-images.githubusercontent.com/6020549/131814272-500d64b3-24ca-47d1-a1ba-5d945c603228.jpg)

Connect from site manager
![fileZilla-3](https://user-images.githubusercontent.com/6020549/131816008-a48410e7-6f55-4b90-b10b-ce3070ecad46.jpg)

Upload file to server
![fileZilla-4](https://user-images.githubusercontent.com/6020549/131816355-6ae0be4b-f4fe-4515-894e-38bf65cef283.jpg)

**Comment by mhsoftware100** [comment]
I changed SDCARD but It doesn't affect

I also make the setting you wanted but It did not work 

I replace the ftp library width the old version.
I have a problem in porting in the last version and in this new version .
The problem is shown in the picture 

![image](https://user-images.githubusercontent.com/77447852/131816282-a2c0ad81-d6c3-4db8-980c-bd6f6c288325.png)


![image](https://user-images.githubusercontent.com/77447852/131816378-237d50f7-793b-4c3a-918a-462f82074acd.png)

**Comment by mhsoftware100** [comment]
This is my site manager setting :

![image](https://user-images.githubusercontent.com/77447852/131816895-994ee2af-7bd3-4cf1-970a-b6de162cf709.png)

![image](https://user-images.githubusercontent.com/77447852/131816970-baa470d8-1f0a-49ca-8063-4a298de7749a.png)


![image](https://user-images.githubusercontent.com/77447852/131817114-bcf6f18e-06d6-4d7d-b775-318d469eef7e.png)

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131817170-91b7662e-e682-4501-8c8d-a9ebd95ade08.png)

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131817212-54edb817-7581-4c42-bcc9-6413ff672923.png)

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131817239-684d8d62-67ed-4254-bda2-89c8130d38ef.png)

**Comment by mhsoftware100** [comment]
![image](https://user-images.githubusercontent.com/77447852/131817264-94a83bc3-805b-4477-b604-943df01e71aa.png)

**Comment by nopnop2002** [comment]
>The problem is shown in the picture

You can see the changes by looking at this.

https://github.com/nopnop2002/esp-idf-ftpServer/commit/a2dfd6667f6890a69f5f5e945d72228e47b06bd8

**Comment by nopnop2002** [comment]
You can get more information by comment out here.

https://github.com/nopnop2002/esp-idf-ftpServer/blob/main/main/ftp.c#L1397


You can find this log.
https://github.com/nopnop2002/esp-idf-ftpServer/blob/main/main/ftp.c#L248
https://github.com/nopnop2002/esp-idf-ftpServer/blob/main/main/ftp.c#L320

**Comment by nopnop2002** [comment]
I have never used an SDSC type card.

![image](https://user-images.githubusercontent.com/77447852/131598288-e204771f-6e37-4eab-a31e-78ad46b2cb52.png)

---

It's mine.

```
Name: SC16G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 15193MB
```

**Comment by NaitikSanas** [comment]
Hello,  @mhsoftware100 we have been also trying to make this project work our end and ran into same issue. after doing some debugging we found that the reason behind FTP client gets stuck at waiting for welcome message is macro `CONFIG_MICROPY_FTPSERVER_TIMEOUT` in `ftp.h` is set to 300 which is causing huge delay between closing previous connection and then start new one for file transfer. in `ftp.c` at line 1080 program waits for too long to re-establish the connection.
thus setting the value of `CONFIG_MICROPY_FTPSERVER_TIMEOUT` around 10 - 15 is fine based of tests i have done.  Hope this helps :)

**Comment by nopnop2002** [comment]
@NaitikSanas 
>delay between closing previous connection and then start new one for file transfer. 

I think it's because the client didn't close the connection properly.

The server waits 300 seconds for input from the client.
If there is no input from the client for 300 seconds, the server will close the connection.
If the client does not close the connection properly, the server will not accept new connections for 300 seconds.
If the client closes the connection correctly, you can immediately make a new connection.

You can see all the logging on the server side by commenting it out here.

https://github.com/nopnop2002/esp-idf-ftpServer/blob/main/main/ftp.c#L1364

```
I (33011) [Ftp]: Data socket disconnected
I (47191) [Ftp]: CMD: QUIT
I (47191) [Ftp]: Send reply: [221 ]
I (47211) [Ftp]: Send reply: OK (6)
```
